### PR TITLE
[WIP]feat: keepExternal

### LINKED ISSUE #204: How to keep "import css" line to the output file?
## Rollup Config
```
export default {
  input: "src/index.js",
  output: {
    file: "dist/index.js",
    format: "cjs"
  },
  plugins: [
    postcss({
      extract: true
    })
  ]
};
```

### src/index.js
```
import "./index.less";
```

## Expected bundle
```
require("./index.css") 
```

- But the actual result is an empty bundle

### PR DESCRIPTION
**Pull request by Himself65**
**DONT MERGE, STILL WIP**

close #204

### CODE REVIEW

**Comment by Himself65** [comment]
use `options.inject`, I think this feature is useless

relatede commits 545dc80 and b364cbe

**Comment by whodoeshua** [comment]
Hi, @Himself65 
I don't think this feature is useless and inject can't cover every scenario.
for example, I want bring out some font file in my library.  Compile as a data url and inject in js file doesn't look like a good idea. Or there are any solution I don't know? Please tell me if there are any solution.
Thanks.

**Comment by Himself65** [comment]
thanks, I realize it.

I will continue to work on this PR

**Comment by nross83** [comment]
@Himself65 Anything I can do to help get this PR merged? I'd really love to use this `keepExternal` in our application.

**Comment by Himself65** [comment]
> @Himself65 Anything I can do to help get this PR merged? I'd really love to use this `keepExternal` in our application.

I think this feature will conflict with other `option`, but unfortunately, I almost forget about what I thought before...

**Pull request closed without merging**
