### PR TITLE
chore: upgrade dependencies

### LINKED ISSUE #324: PostCSS 8
PostCSS 8 was released. It has no breaking changes related to `rollup-plugin-postcss`, most of changes are for plugins. [Full changelog](https://github.com/postcss/postcss/releases/tag/8.0.0).

- [ ] Move `postcss` to `peerDependencies`
- [ ] Update `postcss` version

### PR DESCRIPTION
**Pull request by SASUKE40**
Fix #324

### CODE REVIEW

**Comment by ai** [comment]
LGTM

**Review by wardpeet — APPROVED** [review]
Looks good to me, seems like we don't have any breaking changes

**Comment by spacedawwwg** [comment]
Does the package need a bump?

**Pull request merged**
