### PR TITLE
Add extract option to write combined css and source map

### PR DESCRIPTION
**Pull request by btd**
There is working extract option. I still need to add some tests. I want to gather initial thoughts and opinions about code.

### CODE REVIEW

**Comment by meszaros-lajos-gyorgy** [comment]
Any update on this? Will this get merged?

**Comment by btd** [comment]
@meszaros-lajos-gyorgy it is working (i am using my fork in production already half of the year), but this PR need some rework/cleaning.

**Comment by flying-sheep** [comment]
if you mean “this PR doesn’t actually do what it says anymore” then i believe yes.

**Comment by btd** [comment]
I am closing this, because it requires some work from my side, but i do not see any author activity in this project. 
So i probably will just continue to use my fork.

**Comment by flying-sheep** [comment]
uh, am i missing something or does your fork not actually do anything like that? i can’t find any code that actually extracts the CSS to a file.

**Comment by btd** [comment]
@flying-sheep i am using currently git version of my private repo. 
This PR originally was at this [commit](https://github.com/btd/rollup-plugin-postcss/commit/2dd37e95a54e73ce3b810d53477f7e65d2ce54e6).

**Comment by flying-sheep** [comment]
that commit would work yes, but neither the current master nor the npm version does.

**Comment by btd** [comment]
@flying-sheep yep, i already said i am using version that in private repo. I am sorry i do not see any reason to publish it, as code a bit ugly and i do not want to support it.
If @egoist could add me as colaborator to this repo and npm module i can work on this repo. It is not that hard.

**Comment by flying-sheep** [comment]
but you did publish it: https://www.npmjs.com/package/rollup-plugin-postcss-btd

**Comment by btd** [comment]
@flying-sheep yep, it is easier to use. I mean source code for this version in private repo. Also readme do not show what is actually under hood. It contains some breaking changes with this module and some custom behaviour for my own needs.
You can use it if you will make it work. But i do not recommend =)

**Comment by flying-sheep** [comment]
hmm, i would be awesome to see all of:

* CSS module support with a choice between default export and individual exports (`export default { c: '_c_b4z3z_1' } ` vs `export const c = '_c_b4z3z_1'`)
* a choice between JS-powered style tag injection and CSS file extraction (both working together with exports)
* all in one package, maintained by a bunch of people, not only @egoist, you, me *or* @lmihaidaniel

**Comment by flying-sheep** [comment]
#16 exists and https://github.com/lmihaidaniel/rollup-plugin-postcss-export can do everything!

**Pull request closed without merging**
