### PR TITLE
Added watch functionality for imported files

### PR DESCRIPTION
**Pull request by meszaros-lajos-gyorgy**
Postcss and rollup are [not watching the changes made to the imported files](https://github.com/lmihaidaniel/rollup-plugin-postcss-export/issues/3).

This PR helps solve this rather frustrating issue by providing a watcher, to which the users can dynamically feed the names of files, which they wish to watch. The filenames can be extracted using the `postcss-import`'s or the `postcss-less-engine` plugin's `onImport` handler.

Example rollup config:

```javascript
import postcss from 'rollup-plugin-postcss'
import less from 'postcss-less-engine'

const isWatching = process.argv.includes('-w') || process.argv.includes('--watch')
let watcher

export default [{
  entry: 'src/index.less',
  dest: 'dist/dummy',
  plugins: [
    postcss({
      extensions: ['.less'],
      extract: './dist/test.css',
      getInstance: function(instance){
        // fetch the watcher from the rollup plugin
        watcher = instance.watcher
      },
      plugins: [
        less({
          onImport: function(sources){
            // add sources to watch
            if(isWatching){
              watcher.watch(sources)
            }
          }
        })
      ],
      parser: less.parser
    })
  ]
}]
```

### CODE REVIEW

**Comment by meszaros-lajos-gyorgy** [comment]
Any opinion?

**Comment by lmihaidaniel** [comment]
At a glance looks good to me. What about also using the rollup's watch system, when available ?
Other thing we should add a cache system. nevertheless your pr is worth the attention and will be merged after we merge #33, so we can handle the conflicts much easier

**Comment by lmihaidaniel** [comment]
@meszaros-lajos-gyorgy  please rebase

**Comment by meszaros-lajos-gyorgy** [comment]
@lmihaidaniel I literally spent 3 hours sitting here and trying to do a rebase, but I ended up making a ton of mess in the git history, sorry about that. Please check, if you spot any issues, that the merging might have introduced. If it doesn't workout well, then I'll just create a new branch from the latest master and re-add my changes manually.

**Comment by lmihaidaniel** [comment]
@meszaros-lajos-gyorgy I am very sorry that you spent that amount of work on working for a solution and also for the unfortunate code rebasing.

I'm sorry but I cannot keep merge this after all, it is breaking the current code after running a full test coverage.

I have your pr locally and I am investigating why things are broken. Once I have all the info I'll get back to you.

**Comment by meszaros-lajos-gyorgy** [comment]
Don't sweat it, I'll add the changes tomorrow to the master. It will be much easier, than debugging my mess.

**Pull request merged**
