### PR TITLE
chore: update postcss version to 8

### LINKED ISSUE #324: PostCSS 8
PostCSS 8 was released. It has no breaking changes related to `rollup-plugin-postcss`, most of changes are for plugins. [Full changelog](https://github.com/postcss/postcss/releases/tag/8.0.0).

- [ ] Move `postcss` to `peerDependencies`
- [ ] Update `postcss` version

### PR DESCRIPTION
**Pull request by gustavpursche**
This updates the postcss version to 8 and moves the dependency to `peerDependencies`. Tests are all passing, but there are a couple of deprecation warnings.

Fixes #324

### CODE REVIEW

**Comment by ai** [comment]
LGTM

**Comment by wardpeet** [comment]
If we move it to peerdependencies, it's a breaking change. You'll have to give us some time to see if we can bundle more breaking changes.

**Review by BogdanDarius — APPROVED** [review]

**Comment by GitGangGuy** [comment]
Hi, I'm curious what the status is? I'm waiting for an update to be released so I can use postcss 8 plugins with this rollup plugin...

**Review by bennyg123 — APPROVED** [review]

**Review by shiftgeist — APPROVED** [review]

**Comment by isaacl** [comment]
I didn't realize there was a PR and uploaded #335. They're very similar, I went ahead and updated more of the deps but same idea.

**Comment by patagoniapy** [comment]
Any updates on when this can be merged? Not being able to use postcss-8 over two months down the road is killer.

**Review by SASUKE40 — APPROVED** [review]
LGTM

**Pull request merged**
