### PR TITLE
Fix/extract relative path

### LINKED ISSUE #250: Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths and do not contain invalid characters
I'm getting an error when I try to define a filename for the extract option. 

```
postcss({
  extract: 'dist/test.css',
  …
})
```

v2.4.0:

[!] (plugin postcss) Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths and do not contain invalid characters, received "../test.css".

Works on v2.3.0.

### PR DESCRIPTION
**Pull request by SASUKE40**
Fixes #250

### CODE REVIEW

**Comment by calebeby** [comment]
This should have been released as a major version because this is a breaking change for this use case:

```
postcss({extract: 'dist/style.css'})
```

In 2.8.1 this correctly placed the file in the relative location of `dist/style.css`. In 2.8.2 this does not place the file there

**Comment by SASUKE40** [comment]
related https://github.com/egoist/rollup-plugin-postcss/pull/266

**Comment by SASUKE40** [comment]
> This should have been released as a major version because this is a breaking change for this use case:
> 
> ```
> postcss({extract: 'dist/style.css'})
> ```
> 
> In 2.8.1 this correctly placed the file in the relative location of `dist/style.css`. In 2.8.2 this does not place the file there

I have released two version:
- `v2.9.0@latest` for rollup v1 and v2(it prints some warning messages when using custom extract).
- `v3.0.0@next` only for rollup v2(not allow generate files outside bundle directory).

**Pull request merged**
