### PR TITLE
Remove cssnano

### PR DESCRIPTION
**Pull request by dumistoklus**
I have some resons to delete minimizer from cssnano:
1) projects which doesn't use cssnano as minizier anyway upload it
2) using one tool in other tool is antipattern

Developers can use cssnano as plugin
```
// rollup.config.js
import postcss from 'rollup-plugin-postcss'
import cssnano from 'cssnano'

export default {
  plugins: [
    postcss({
      plugins: [
        cssnano(/* cssnano options */),
      ]
    })
  ]
}
```

### CODE REVIEW

**Comment by dumistoklus** [comment]
@egoist Could you review code and merge it?

**Comment by rproserpio** [comment]
I'm not a maintainer of the project (and the project looks rather unmainteined) but isn't there a big difference of behavior with this pr?
Right now every input file is processed separately by postcss while cssnano works on the concatenated output. 
With your pr the minification can only be done separately in each file before the concat.

**Comment by wardpeet** [comment]
@dumistoklus why can't you set `minimize` to false? Can you create an issue instead?

**Comment by dumistoklus** [comment]
> @dumistoklus why can't you set `minimize` to false? Can you create an issue instead?

Because I don't want to download hundred extra packages

**Pull request closed without merging**
