### PR TITLE
Transform named exported classNames to accepted js var names and other fixes

### PR DESCRIPTION
**Pull request by lmihaidaniel**
- fixed wrong sourcemap reference with manual destination (#32, #33)
- added getExportNamed param to allow/ named exports when used with css
modules (#27, #30)
- when using name exports, all the classNames that contains dashes, or
they are js protected names, will be transformed to usable js names.  (#27, #28)
- name transformations are logged out for usage information.
- added new unit tests and updated existing tests to cover more scenarios

### CODE REVIEW

**Comment by lmihaidaniel** [comment]
@egoist can you take a look and give your opinion regarding the proposed solution of named exported issues ?

**Comment by lmihaidaniel** [comment]
ping @egoist

**Comment by FezVrasta** [comment]
Any news? It's blocking us :-(

**Comment by FezVrasta** [comment]
@lmihaidaniel looks like you already have write permissions on this repo, may you go ahead and merge this PR?

**Comment by egoist** [comment]
what about simply *dash to underscore* and prefixing js keywords with underscore?

**Comment by FezVrasta** [comment]
@egoist anything that changes the original class name would make this plugin useless to most of us.

I need something compatible with the common Webpack postcss loader, that works exporting the classnames exactly as they are without modifying anything.

If I have:

```
.Button
  &__large
  
  &--large
```

if we replace `--` with `__` we'll have a naming conflict.
But aside from this, if I reference `styles['Button--large']` I expect it to work.

**Comment by egoist** [comment]
@FezVrasta it's only changed in named exports.

**Comment by egoist** [comment]
anyways current solution doesn't looks bad to me. but maybe add a `convertClassName` option customize it for named exports?

**Comment by lmihaidaniel** [comment]
@egoist You refer to a callback which will overwrite the [`escapeClassNameDashes`](https://github.com/egoist/rollup-plugin-postcss/pull/34/files#diff-1fdf421c05c1140f6d71444ea2b27638R142) so that the user can have his own customisable class names naming ?

**Comment by egoist** [comment]
Ah yes.

**Comment by FezVrasta** [comment]
@egoist ah ok! yes that would be great

**Comment by egoist** [comment]
You can merge it if you think it's ready to go 👌

**Comment by egoist** [comment]
Released in v0.5.4

**Pull request merged**
