### PR TITLE
Pass outputSourceFiles to less loader

### PR DESCRIPTION
**Pull request by michaeland**
This matches the output of sass-loader (includes "sourcesContent" property on sourcemap),
and fixes sourcemaps for less files when dest path isn't served on a public URL.

### CODE REVIEW

**Comment by michaeland** [comment]
Let me know if this is worth considering and I'll look to update the snapshots to pass the tests.

Currently it seems like scss and css are allowed to have the 'sourcesContent' property in the map, but stylus and less aren't. Was this intentional to reduce the map size, or just happenstance?

Otherwise I get this in Chrome when developing, which isn't great:
```
Could not load content for http://XXXXX/src/styles/main.less (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```

Thanks

**Comment by SASUKE40** [comment]
There are real inconsistencies here.
IMHO, `sourcesContent` should be generated for every type.

**Comment by michaeland** [comment]
Sorry, first time pull request, didn't mean to close it (I deleted the branch after rebasing onto master, whoops).

I've updated the branch so `sourcesContent` is included for both less and stylus [here](https://github.com/michaeland/rollup-plugin-postcss/commit/10f3638cc1e6fdaf4a79884094f59e19080b6c22), and updated the snapshots [here](https://github.com/michaeland/rollup-plugin-postcss/commit/7b50f2698828d4fba09eabdd7d9b5b5249bf0a82).

Is there a way to reopen this PR, or should I submit separately?

Thanks,
Michael

**Comment by SASUKE40** [comment]
That is ok to create a new PR.
Just take it easy, dude.

**Pull request closed without merging**
