### PR TITLE
Add generic support for watching imported dependencies + Stylus support specifically

### PR DESCRIPTION
**Pull request by anttikissa**
This PR does two things:

- Gives loaders the ability to return `dependencies` which are then passed on to rollup, enabling it to track imported files when run in watch mode. Rollup supports this from version 0.61 onwards. (This won't break on older versions, but won't do anything either.)
- Add this ability to stylus-loader.js (which was very straightforward)

It's a Stylus-specific fix to https://github.com/egoist/rollup-plugin-postcss/issues/37 and also a good starting point if someone wants to look into implementing this for other loaders. 

No tests, yet, sorry!

Feedback about code style etc. is welcome.

### CODE REVIEW

**Comment by anttikissa** [comment]
I finally did write some tests for using `rollup-plugin-postcss` with rollup.watch(). The first one tests that importing a CSS file (or a Stylus file, really) from a JS file starts to listen to changes in the CSS file, and the second one tests that importing a CSS file from a CSS file does the same. 

Unfortunately, watching imported dependencies is only possible from rollup 0.61 onwards, and upgrading to rollup 0.61 broke some other tests, apparently mostly because the order of rules in generated CSS files changes. The last commit of this PR (fe6e4c5d) downgrades the rollup back to 0.57 and comments out the test that depends on the upgrade, so the branch still passes all tests. Please revert the last PR once the other tests have been fixed to work with the newer rollup.

**Comment by anttikissa** [comment]
Added tests for watching dependencies imported from CSS (Stylus really), and dependencies in general.

The first one ('rollup.watch() watches directly imported .styl files') tests that importing a Stylus file from a JS file causes the watcher to listen to changes in the Stylus file; the second one ('rollup.watch() watches indirectly imported .styl files') tests that importing a Stylus file from another Stylus file does the same.

Unfortunately, watching imported dependencies is only possible from rollup 0.61 onwards, and upgrading to rollup 0.61 broke some snapshot tests (apparently mostly because the order of the rules in the generated CSS changes). The last commit of this PR (fe6e4c5d) downgrades the rollup back to 0.57 and comments out the test that depended on the upgrade, so the branch still passes all tests. Please revert the last PR once the snapshot tests have been fixed to work with the newer rollup.

**Comment by anttikissa** [comment]
Added tests for watching dependencies imported from CSS (Stylus really), and dependencies in general.

The first one ('rollup.watch() watches directly imported .styl files') tests that importing a Stylus file from a JS file causes the watcher to listen to changes in the Stylus file; the second one ('rollup.watch() watches indirectly imported .styl files') tests that importing a Stylus file from another Stylus file does the same.

Unfortunately, watching imported dependencies is only possible from rollup 0.61 onwards, and upgrading to rollup 0.61 broke some snapshot tests (apparently mostly because the order of the rules in the generated CSS changes). The last commit of this PR (fe6e4c5d) downgrades the rollup back to 0.57 and comments out the test that depended on the upgrade, so the branch still passes all tests. Please revert the last PR once the snapshot tests have been fixed to work with the newer rollup.

**Comment by anttikissa** [comment]
Added tests for watching dependencies imported from CSS (Stylus really), and dependencies in general.

The first one ('rollup.watch() watches directly imported .styl files') tests that importing a Stylus file from a JS file causes the watcher to listen to changes in the Stylus file; the second one ('rollup.watch() watches indirectly imported .styl files') tests that importing a Stylus file from another Stylus file does the same.

Unfortunately, watching imported dependencies is only possible from rollup 0.61 onwards, and upgrading to rollup 0.61 broke some snapshot tests (apparently mostly because the order of the rules in the generated CSS changes). The last commit of this PR (fe6e4c5d) downgrades the rollup back to 0.57 and comments out the test that depended on the upgrade, so the branch still passes all tests. Please revert the last PR once the snapshot tests have been fixed to work with the newer rollup.

**Comment by anttikissa** [comment]
I added some tests and wrote a comment here about it but GitHub is acting strangely so I can't see them anymore. The code is here though: https://github.com/anttikissa/rollup-plugin-postcss/

**Comment by sormy** [comment]
For sass/scss support:

```
diff --git a/src/sass-loader.js b/src/sass-loader.js
index d0d6cde..3083058 100644
--- a/src/sass-loader.js
+++ b/src/sass-loader.js
@@ -72,7 +72,8 @@ export default {
         }).then(res =>
           resolve({
             code: res.css.toString(),
-            map: res.map && res.map.toString()
+            map: res.map && res.map.toString(),
+            dependencies: res.stats.includedFiles
           })
         ).catch(reject)
       )
```

**Comment by vinkla** [comment]
What can one do to help move this pull request forward? What is left to do here?

**Comment by egoist** [comment]
Can you update it for Rollup 1? 

> Returning "dependencies" from plugin transform hook is deprecated for using this.addWatchFile() instead.

**Comment by anttikissa** [comment]
I'm happy to inform that this pull request is no longer relevant with the most recent version of rollup-plugin-postcss (2.0.3) and rollup (1.1.2 and 1.3.2 tested). Plain CSS (using `postcss-import`), Stylus, SCSS, and Less files now all add their dependencies as they are supposed to. I tested by setting up a simple main.js that imports several style files indirectly and observed the results when the imported files were changed. Also the `watchFiles` property that comes as the result of BUNDLE_END event includes all the files:
```
{ code: 'BUNDLE_END',
  input: 'example/main.js',
  output: [ '/Users/antti/code/rollup-plugin-postcss/out.js' ],
  duration: 250,
  result:
   { cache: { modules: [Array], plugins: {} },
     watchFiles:
      [ '/Users/antti/code/rollup-plugin-postcss/example/main.js',
        '/Users/antti/code/rollup-plugin-postcss/example/main.styl',
        '/Users/antti/code/rollup-plugin-postcss/example/main.scss',
        '/Users/antti/code/rollup-plugin-postcss/example/main.css',
        '/Users/antti/code/rollup-plugin-postcss/example/main.less',
        '/Users/antti/code/rollup-plugin-postcss/example/imported.styl',
        '/Users/antti/code/rollup-plugin-postcss/node_modules/style-inject/dist/style-inject.es.js',
        '/Users/antti/code/rollup-plugin-postcss/example/imported.less',
        '/Users/antti/code/rollup-plugin-postcss/example/imported.scss',
        '/Users/antti/code/rollup-plugin-postcss/example/imported.css' ],
     generate: [Function: generate],
     write: [Function: write] } }
```

**Pull request closed without merging**
