### PR TITLE
Add support for index.scss in sass-loader module resolve

### PR DESCRIPTION
**Pull request by peterhass**
https://github.com/egoist/rollup-plugin-postcss/issues/333

This change makes it able to resolve 'main' files from the package name alone. Webpack sass-loader also does it in this way.

`@import "~foo";` resolves to `node_modules/foo/_index.scss`

### CODE REVIEW

**Comment by benmccann** [comment]
@peterhass it looks like this PR will need to be rebased

**Comment by peterhass** [comment]
@benmccann Merged in newest master. I was a bit surprised about the linter rule not allowing `array.reduce` but I hope the change I did is alright.

`codecov/patch` is still failing because the error handling in `tryToResolve` isn't tested. I assume it was the same way before my change - any action needed from my side?

**Comment by peterhass** [comment]
Hey @benmccann, is there still something wrong with this PR? Can I help in any way to get this reviewed & merged?

**Comment by benmccann** [comment]
I'm not a maintainer and am not the person to ask

**Comment by aweng-chwy** [comment]
@peterhass I know this PR opened awhile ago, but any reason why it's closed? I would like to see this fix get in

**Comment by peterhass** [comment]
> @peterhass I know this PR opened awhile ago, but any reason why it's closed? I would like to see this fix get in

No. Kept using this change as a fork for a while but since I was unable to get it merged I migrated all my usages back.

Hard to argue if the behavior of sass-loader is the gold standard here.

**Pull request closed without merging**
