### PR TITLE
WIP: feat: use multiEntry input

### PR DESCRIPTION
**Pull request by chmelevskij**
Another take on multientry input. Keeping in draft as it needs more tests

### CODE REVIEW

**Comment by chmelevskij** [comment]
@atompkins @BogdanDarius @daviddelusenet @michaeland @emjaksa

this PR is based on the previous one with fixes for the empty imports. I passes the current test suite, but still needs more tests. Could you please verify it works for you and if possible provide some repro of your setups?

**Comment by michaeland** [comment]
I've just quickly swapped this out on the project i'm working on at the moment (so not a slimmed down case), but it's come through with an empty CSS file again:

```

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzaXRlLmNzcyJ9 */
```

but strangely, with a corresponding site.css.map file:
```
{"version":3,"sources":[],"names":[],"mappings":"","file":"static/site.css"}
```

This setup probably isn't regular (custom static site gen plugin), so I'll try and get you a slimmed down reproduction later on.

Here's the css part of my conf at the moment:

```
const css = (emit = true, prod = false) => postcss({
    plugins: [
        emit && postcssImport(),
        emit && postcssPresetEnv({ stage: 0 }),
        emit && postcssCopy({
            dest: './dist/static',
            template: '[name].[hash].[ext]'
        }),
    ],
    extract: emit && 'static/site.css',
    minimize: prod,
    sourceMap: true,
    use: {
        less: { 
            // allows url asset paths to be relative
            rewriteUrls: 'all',
            // allows same aliases as js imports
            plugins: [ new LessAlias({ aliases: noAt() }) ]
        }
    }
})
```

```
const staticGen = {
    input: [
        'src/pages/index.js'
    ],
    output: {
        // output to site directory
        dir: 'dist',
        format: 'cjs',
        sourcemap: 'inline'
    },
    plugins: [
        …
        css(),
        …
    ]
}

export default [staticGen]
```

**Comment by michaeland** [comment]
I've put a stripped-down build here: https://github.com/michaeland/postcss-test

to test, I cloned [your repo](https://github.com/chmelevskij/rollup-plugin-postcss/tree/feat/support-multiple-entry-points), switched to the `support-multiple-entry-points` branch, ran `npm run build` and then `yarn link`’ed it into my test project.

On the face of it, it seems like it doesn't like any css imports that aren't at the top level. For example, if I include another js file from the main entry point:

in `src/index.js`:
```
import anotherSrc from './another.js'
```

in `src/another.js`:
```
import './test.less'
```

That results in an empty `dist/site.css`:
```

/*# sourceMappingURL=site.css.map */
```

but if I skip out the `another.js` import, and do it directly (in `src/index.js`):
```
import './test.less'
```

That results in the correct css file:
```
body {
  background: red;
}

/*# sourceMappingURL=site.css.map */
```


Hope that helps!

**Comment by chmelevskij** [comment]
>in src/index.js:
>
> import anotherSrc from './another.js'

Had to add `console.log(anotherSrc)` because otherwise module gets tree-shaken. But still the same issue.

**Comment by ops1ops** [comment]
Hi, how soon are you planning to release this feature?

**Comment by chmelevskij** [comment]
> Hi, how soon are you planning to release this feature?

Can't say for sure. There are some issues from rollup v2 which make it a bit more complicated to work for all the current cases.

**Comment by chmelevskij** [comment]
Closing this as there are alternatives for this plugin. Found out that https://github.com/Anidetrix/rollup-plugin-styles does the 80% of what I needed so won't be continuing with this as there are a lot of thing which need to be updated for it to work correctly.

**Comment by ops1ops** [comment]
and where is multy entry support in rollup-plugin-styles? I didnt find any example of it

**Comment by chmelevskij** [comment]
It uses the fact that rollup has ability to understand input as object E.G.
```javascript
 input: {
   entry1: 'path/to/entry1.js'
   entry2: 'path/to/entry2.js'
  // and so on
}
```

Any of the styles used in those entries will be genrated and put next to the entry. To set asset name you can use [assetFilenames](https://rollupjs.org/guide/en/#outputassetfilenames) this also understands slashes in it and will create corresponding directories.

From personal usecase
```javascript
const moduleOutput = {
    format: 'esm',
    dir: 'dist',
    entryFileNames: 'resources/vertical/[name]/LOCAL/index.mjs',
    chunkFileNames: 'vendor/[name].[hash].js',
    assetFileNames: 'resources/vertical/[name]/LOCAL/index[extname]',
    sourcemap: true,
};
```

hope this helps

**Pull request closed without merging**
