### PR TITLE
fix: add missing warning.message

### PR DESCRIPTION
**Pull request by lemon-clown**
- https://github.com/rollup/rollup/blob/c0c206e2a8a892fdb0e4f9b25b0a817b733a072f/cli/run/batchWarnings.ts#L178

- https://github.com/rollup/rollup/blob/c0c206e2a8a892fdb0e4f9b25b0a817b733a072f/cli/run/batchWarnings.ts#L183

- https://github.com/postcss/postcss/blob/d7a1923008cf5c40c9b327ef37bc852f90252d2a/lib/postcss.d.ts#L420

### CODE REVIEW

**Comment by SASUKE40** [comment]
I could not reproduce the warning case from rollup. Could you add a unit test for it?

**Comment by lemon-clown** [comment]
I'm sorry, this is a bit difficult to me. 
I found this bug when using `postcss-url` in combination, and I create a [demo](https://github.com/lemon-clown/rollup-plugin-postcss/tree/issue-260/issue-260) to show you the problems I encountered more clearly:

  1. Download [the demo project](https://github.com/lemon-clown/rollup-plugin-postcss/tree/issue-260/issue-260)
  2. Run `yarn install`
  3. Run `yarn build`

Then you will get the following message: 
    image

But the result we expect is:
    image

**Comment by SASUKE40** [comment]
> I'm sorry, this is a bit difficult to me.
> I found this bug when using `postcss-url` in combination, and I create a [demo](https://github.com/lemon-clown/rollup-plugin-postcss/tree/issue-260/issue-260) to show you the problems I encountered more clearly:
> 
> 1. Download [the demo project](https://github.com/lemon-clown/rollup-plugin-postcss/tree/issue-260/issue-260)
> 2. Run `yarn install`
> 3. Run `yarn build`
> 
> Then you will get the following message:
> image
> 
> But the result we expect is:
> image

LGTM, I will tag it soon.

**Comment by SASUKE40** [comment]
image
image

**Comment by lemon-clown** [comment]
Thank you for updating & publishing the code so quickly!
Is the last picture to show that my demo does not work properly? As the release is published, you can upgrade the `rollup-plugin-postcss` to the latest version and rerun `yarn build` to verify the result.

**Pull request merged**
