### PR TITLE
Add option to combine all style tags to one

### PR DESCRIPTION
**Pull request by btd**
I want to get initial thoughts. I used concat-with-sourcemaps to make it possible to generate sourcemap for concatenated styles.
Also it looks with this option, it does not looks usefull to have separate style tags. 
What do you think about naming, code etc?

### CODE REVIEW

**Comment by egoist** [comment]
It would be perfect if you can add an `extract` option. I guess it's as easy as:

```js
if (options.extract) {
  const extractTo = typeof options.extract === 'string' ? options.extract : 'styles.css';
  fs.writeFileSync(extractTo, concat.content);
}
```

How do you think?

**Comment by btd** [comment]
Yep, i initially thought about it, but decide to show first. Some people do not like when a lot of features happen in one PR. Also there is one more PR for .extract feature.

**Comment by btd** [comment]
Also i have one question. You are returning postcss css sourcemap to rollup. But currently it is not correct. Beacause you return sourcemap for css, but you return js code that adds style tag. So you return sourcemap not for right code. So it looks it is not working now.

**Comment by egoist** [comment]
@btd oops, didn't even realize that.

**Comment by btd** [comment]
Just to update progress. While working on extract option i found one blocking me [bug](https://github.com/rollup/rollup/pull/1056). I will create PR after that issue resolved.

**Pull request merged**
